Pages/Admin/UserManagement/AddAdmin.cshtml.cs
 using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Spoonful.Models;
using Spoonful.Services;
using System.ComponentModel.DataAnnotations;

namespace Spoonful.Pages.Admin.UserManagement
{
    public class AddAdminModel : PageModel
    {
		private readonly UserManager<CustomerUser> _userManager;
		private readonly CustomerUserService _userService;
		public AddAdminModel(UserManager<CustomerUser> userManager, CustomerUserService userService)
		{
			_userManager = userManager;
			_userService = userService;
		}

		[BindProperty]
        public Register RModel { get; set; }
        public void OnGet()
        {
        }

		public async Task<IActionResult> OnPostAsync()
		{
			if (!ModelState.IsValid)
			{
				return Page();
			}

			var user = new CustomerUser()
			{
				UserName = RModel.UserName,
				RequirePassChange = RModel.RequirePassChange
			};
			var result = await _userManager.CreateAsync(user, RModel.Password);
			if (result.Succeeded)
			{
				//var userclaims = await userManager.GetClaimsAsync(user);
				//await userManager.RemoveClaimAsync(user, );
				//await userManager.AddClaimAsync(user, new Claim(ClaimTypes.NameIdentifier, RModel.UserName));
				await _userService.SetUserRoleAsync(user.UserName, Roles.Admin);
				TempData["FlashMessage.Text"] = "Created account successfully";
				TempData["FlashMessage.Type"] = "success";
				return RedirectToPage("Index");
			}
			foreach (var error in result.Errors)
			{
				ModelState.AddModelError("", error.Description);
			}
			return Page();
		}

		public class Register
		{
			[Required]
			[Display(Name = "Username")]
			public string UserName { get; set; }

			[Required]
			[DataType(DataType.Password)]
			public string Password { get; set; }

			[Required]
			[DataType(DataType.Password)]
			[Compare(nameof(Password), ErrorMessage = "Passwords must match")]
			public string ConfirmPassword { get; set; }
			public bool RequirePassChange { get; set; }
		}
	}
}

Pages/Admin/UserManagement/Index.cshtml.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.WebUtilities;
using Microsoft.EntityFrameworkCore;
using Spoonful.Models;
using Spoonful.Services;
using System.Globalization;
using System.Security.Claims;
using System.Text.Encodings.Web;
using System.Text;
using System.ComponentModel.DataAnnotations;

namespace Spoonful.Pages.Admin.UserManagement
{
    public class IndexModel : PageModel
    {
        private readonly AuthDbContext _db;
        private readonly UserManager<CustomerUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly INotyfService _toastService;
        private readonly IEmailService _emailService;

        public IndexModel(AuthDbContext db, UserManager<CustomerUser> userManager, RoleManager<IdentityRole> roleManager, INotyfService notyfService, IEmailService emailService)
        {
            _db = db;
            _userManager = userManager;
            _roleManager = roleManager;
            _toastService = notyfService;
            _emailService = emailService;
        }

        public List<CustomerUser> Users { get; set; }
        public List<CustomerDetails> CustomerDetails { get; set; }
        public List<AdminDetails> AdminDetails { get; set; }
        public List<DriverDetails> DriverDetails { get; set; }
        public List<IdentityRole> RoleList { get; set; }

        [BindProperty]
        public List<string> RoleInput { get; set; }
        [Required]
        [BindProperty]
        public string UserEmail { get; set; }

        public async Task OnGet()
        {
            Users = _userManager.Users.Include(u => u.UserDetails).ToList();
            CustomerDetails = _db.CustomerDetails.Include(d => d.User).ToList();
            AdminDetails = _db.AdminDetails.Include(d => d.User).ToList();
            DriverDetails = _db.DriverDetails.Include(d => d.User).ToList();
            //Ddeets = _db.Users.Include(d => d.UserDetails).Where(d => d.UserDetails.UserType == Roles.Driver);
            RoleList = _roleManager.Roles.Where(r => r.Name != "RootUser" && r.Name != "Admin" && r.Name != "Customer" && r.Name != "Driver").ToList();
        }

        public async Task<IActionResult> OnPostDeleteUserAsync(string name)
        {
            var user = await _userManager.FindByNameAsync(name);
            await _userManager.DeleteAsync(user);

            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostAddRolesAsync(string name)
        {
            var user = await _userManager.FindByNameAsync(name);
            var currentRoles = await _userManager.GetRolesAsync(user);
            currentRoles = currentRoles.Where(r => r != "RootUser" && r != "Admin" && r != "Customer" && r != "Driver").ToList();
            await _userManager.RemoveFromRolesAsync(user, currentRoles);
            var result = await _userManager.AddToRolesAsync(user, RoleInput);
            if (result.Succeeded)
            {
                _toastService.Success("Added roles successfully");

            }
            foreach (var error in result.Errors)
            {
                Console.WriteLine(error);
            }
            return RedirectToPage();

        }

        public async Task<IActionResult> OnPostAdminCreateUser()
        {
            if (!ModelState.IsValid)
            {
                Users = _userManager.Users.Include(u => u.UserDetails).ToList();
                CustomerDetails = _db.CustomerDetails.Include(d => d.User).ToList();
                AdminDetails = _db.AdminDetails.Include(d => d.User).ToList();
                DriverDetails = _db.DriverDetails.Include(d => d.User).ToList();
                RoleList = _roleManager.Roles.Where(r => r.Name != "RootUser" && r.Name != "Admin" && r.Name != "Customer" && r.Name != "Driver").ToList();
                _toastService.Error("Email field is required");
                return Page();
            }
            var newUser = new CustomerUser
            {
                Email = UserEmail,
                UserName = UserEmail
            };
            var result = await _userManager.CreateAsync(newUser);
            if (!result.Succeeded)
            {
                foreach (var error in result.Errors)
                {
                    _toastService.Error($"Something went wrong - {error.Description}");
                }
                return RedirectToPage();
            }
            var resultRole = await _userManager.AddToRolesAsync(newUser, RoleInput);
            if (!resultRole.Succeeded)
            {
                foreach (var error in resultRole.Errors)
                {
                    _toastService.Error($"Something went wrong - {error.Description}");
                }
                return RedirectToPage();
            }
            var code = await _userManager.GenerateEmailConfirmationTokenAsync(newUser);
            code = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(code));
            var callbackUrl = Url.Page(
            "/Account/CreateAdmin",
            pageHandler: null,
                values: new { code = code, username = newUser.UserName },
                protocol: Request.Scheme);

            var emailresult = _emailService.SendEmail(
                UserEmail,
                "Spoonful Admin Setup",
                $"Please set up your admin account by <a href='{HtmlEncoder.Default.Encode(callbackUrl)}'>clicking here</a>.",
                null,
                null);

            if (!emailresult)
            {
                _toastService.Error("Email failed to send");
            }
            _toastService.Success("Sent instructions to email if email is valid");
            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostDriverCreateUser()
        {
            if (!ModelState.IsValid)
            {
                Users = _userManager.Users.Include(u => u.UserDetails).ToList();
                CustomerDetails = _db.CustomerDetails.Include(d => d.User).ToList();
                AdminDetails = _db.AdminDetails.Include(d => d.User).ToList();
                DriverDetails = _db.DriverDetails.Include(d => d.User).ToList();
                RoleList = _roleManager.Roles.Where(r => r.Name != "RootUser" && r.Name != "Admin" && r.Name != "Customer" && r.Name != "Driver").ToList();
                _toastService.Error("Email field is required");
                return Page();
            }
            var newUser = new CustomerUser
            {
                Email = UserEmail,
                UserName = UserEmail
            };
            var result = await _userManager.CreateAsync(newUser);
            if (!result.Succeeded)
            {
                foreach (var error in result.Errors)
                {
                    _toastService.Error($"Something went wrong - {error.Description}");
                }
                return RedirectToPage();
            }
            var code = await _userManager.GenerateEmailConfirmationTokenAsync(newUser);
            code = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(code));
            var callbackUrl = Url.Page(
            "/Account/CreateDriver",
            pageHandler: null,
                values: new { code = code, username = newUser.UserName },
                protocol: Request.Scheme);

            var emailresult = _emailService.SendEmail(
                UserEmail,
                "Spoonful Driver Setup",
                $"Please set up your driver account by <a href='{HtmlEncoder.Default.Encode(callbackUrl)}'>clicking here</a>.",
                null,
                null);

            if (!emailresult)
            {
                _toastService.Error("Email failed to send");
            }
            _toastService.Success("Sent instructions to email");
            return RedirectToPage();
        }
    }
}

Pages/Admin/UserManagement/Roles.cshtml.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Spoonful.Models;

namespace Spoonful.Pages.Admin.UserManagement
{
    public class RolesModel : PageModel
    {
        private readonly AuthDbContext _db;
        private readonly UserManager<CustomerUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly INotyfService notyfService;

        public RolesModel(AuthDbContext db, UserManager<CustomerUser> userManager, RoleManager<IdentityRole> roleManager, INotyfService notyfService)
        {
            _db = db;
            _userManager = userManager;
            _roleManager = roleManager;
            this.notyfService = notyfService;
        }

        public List<IdentityRole> Roles { get; set; }
        public IdentityRole Role { get; set; }
        public List<CustomerUser> UsersinRole { get; set; }
        public List<CustomerUser> UsersNotinRole { get; set; }
        [BindProperty]
        public string SelectedUserName { get; set; }
        [BindProperty]
        public string RoleName { get; set; }

        public async Task<IActionResult> OnGetAsync(string name)
        {
            if (name == "All")
            {
                Roles = _roleManager.Roles.ToList();

            }
            else
            {
                Role = _roleManager.Roles.FirstOrDefault(r => r.Name == name);
                if (Role == null || Role.Name == "Customer" || Role.Name == "Driver")
                {
                    return NotFound();
                }
                UsersinRole = (await _userManager.GetUsersInRoleAsync(Role.Name)).ToList();
                UsersNotinRole = _userManager.Users.Where(u => !UsersinRole.Contains(u) && u.UserDetails.UserType == "Admin").ToList();
            }
            return Page();
        }

        //public IActionResult OnGetRoles()
        //{
        //    Roles = _roleManager.Roles.ToList();
        //    return new JsonResult(Roles);
        //}

        public async Task<IActionResult> OnPost()
        {
            if (RoleName == null)
            {
                Roles = _roleManager.Roles.ToList();
                notyfService.Error("Role Name cannot be empty");
                return Page();
            }
            if (!await _roleManager.RoleExistsAsync(RoleName))
            {
                await _roleManager.CreateAsync(new IdentityRole(RoleName));
                notyfService.Success("Successfully added role.");
                return RedirectToPage();

            }
            notyfService.Error("This role already exists.");
            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostDelete(string name)
        {
            var role = await _roleManager.FindByNameAsync(name);
            await _roleManager.DeleteAsync(role);
            notyfService.Success("Successfully deleted role.");
            return Redirect("/Admin/UserManagement/Roles/All");
        }

        public async Task<IActionResult> OnPostAddUserToRole(string name)
        {
            var user = await _userManager.FindByNameAsync(SelectedUserName);
            await _userManager.AddToRoleAsync(user, name);
            return RedirectToPage();
        }
        public async Task<IActionResult> OnPostDeleteUserFromRole(string name, string username)
        {
            var user = await _userManager.FindByNameAsync(username);
            await _userManager.RemoveFromRoleAsync(user, name);
            return RedirectToPage();
        }
    }
}

Pages/Admin/UserManagement/AddAdmin.cshtml
@page
@model Spoonful.Pages.Admin.UserManagement.AddAdminModel
@{
}
<form method="post">
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary pl-3 display-6">Add Admin User</h2>
			<br/>

		</div>
		<div asp-validation-summary="All"></div>
		<div class="mb-3">
			<label asp-for="RModel.UserName"></label>
			<input asp-for="RModel.UserName" class="form-control">
			<span asp-validation-for="RModel.UserName" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="RModel.Password"></label>
			<input asp-for="RModel.Password" class="form-control">
			<span asp-validation-for="RModel.Password" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="RModel.ConfirmPassword"></label>
			<input asp-for="RModel.ConfirmPassword" class="form-control">
			<span asp-validation-for="RModel.ConfirmPassword" class="text-danger"></span>
		</div>
		<div class="form-check mb-3 mb-md-0">
			<input class="form-check-input" type="checkbox" asp-for="RModel.RequirePassChange" />
			<label class="form-check-label" asp-for="RModel.RequirePassChange"> Require user to change password on first login</label>
		</div>

		<button type="submit" class="blue-btn-a" style="width:150px;">Create</button>
		<a asp-page="Index" class="light-btn-a" style="width:150px";> Back to List</a>
	</div>
</form>

Pages/Admin/UserManagement/Index.cshtml
@page
@using Microsoft.AspNetCore.Identity;
@using Spoonful.Models;
@using Spoonful.Services;
@model Spoonful.Pages.Admin.UserManagement.IndexModel
@inject UserManager<CustomerUser> UserManager
@inject RoleManager<IdentityRole> RoleManager
@{
    
}
<div class="card p-3">
    <h2 class="card-title">Customer Users</h2>
    <table
        id="Customertable"
        data-toggle="table"
        data-search="true"
        data-click-to-select="true"
        data-pagination="true"
        data-id-field="email"
        data-page-list="[10, 25, 50, 100, all]"
        data-sortable="true">
        <thead>
            <tr>
                <th data-field="state" data-checkbox="true"></th>
                <th data-field="name" data-sortable="true">Name</th>
                <th data-field="email" data-sortable="true">Email</th>
                <th data-field="username" data-sortable="true">Username</th>
                <th data-field="lastLogin" data-sortable="true" data-formatter="dateFormatter">Last Login</th>
                <th data-field="dateCreated" data-sortable="true" data-formatter="dateFormatter">Date Created</th>
                <th data-field="activity" data-sortable="true">Activity</th>
                <th data-field="buttons">Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.CustomerDetails)
            {
                <tr>
                    <td></td>
                    <td>@item.User.FirstName @item.User.LastName</td>
                    <td>@item.User.Email</td>
                    <td>@item.User.UserName</td>
                    <td>@item.User.LastLogin</td>
                    <td>@item.User.DateCreated</td>
                    <td>Nothing to see here</td>
                </tr>
            }
        </tbody>
    </table>

</div>
<div class="card p-3">
    <div id="admintoolbar" class="d-flex">
        <div class="dropdown" >
            <button class="blue-btn-10" type="button" data-bs-toggle="dropdown" data-bs-auto-close="outside" aria-expanded="false">
                Add Admin
            </button>
            <form class="px-3 py-3 dropdown-menu" asp-page-handler="AdminCreateUser" method="post" style="width: 20em">
                <div class="mb-3">
                    <label asp-for="UserEmail" class="form-label">Email address</label>                                                             
                    <input type="email" class="form-control" asp-for="UserEmail" placeholder="email@example.com">
                    <span class="text-danger" asp-validation-for="UserEmail"></span>
                </div>
                <div class="mb-3">
                    <p class="form-label">Roles</p>
                    @if (RoleManager.Roles.Count() > 4)
                    {
                        @foreach (var role in RoleManager.Roles)
                        {
                            if (Roles.Protected.Contains(role.Name))
                            {
                                continue;
                            }
                            <input id="RoleInput" name="RoleInput" type="checkbox" value="@role.Name">
                            @Html.Label(role.Name, role.Name)
                            <br />
                        }
                    } else
                    {
                        <p class="text-muted">No Roles available</p>
                    }
                </div>
                <button type="submit" class="btn btn-primary">Create Admin</button>
                
            </form>
        </div>
        <a class="light-btn-a" asp-page="Roles">Admin Roles</a>
    </div>
    <h2 class="card-title">Admin Users</h2>
    <table id="Admintable"
        data-toggle="table"
        data-search="true"
        data-click-to-select="true"
        data-pagination="true"
        data-id-field="email"
        data-page-list="[10, 25, 50, 100, all]"
        data-sortable="true"
           data-toolbar="#admintoolbar"
        data-toolbar-align="left">
        <thead>
            <tr>
                <th data-field="state" data-checkbox="true"></th>
                <th data-field="name" data-sortable="true">Name</th>
                <th data-field="email" data-sortable="true">Email</th>
                <th data-field="username" data-sortable="true">Username</th>
                <th data-field="lastLogin" data-sortable="true" data-formatter="dateFormatter">Last Login</th>
                <th data-field="dateCreated" data-sortable="true" data-formatter="dateFormatter">Date Created</th>
                <th data-field="roles" data-sortable="true">Roles</th>
                <th data-field="buttons">Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.AdminDetails)
            {
                <tr>
                    <td></td>
                    <td>@item.User.FirstName @item.User.LastName</td>
                    <td>@item.User.Email</td>
                    <td>@item.User.UserName</td>
                    <td>@item.User.LastLogin</td>
                    <td>@item.User.DateCreated</td>
                    <td>
                        <div class="d-flex justify-content-evenly">

                        @foreach (var role in await UserManager.GetRolesAsync(item.User))
                        {
                                <a asp-page="Roles" asp-route-name="@role" class="btn btn-outline-info ">@role</a>
                        }
                        </div>
                    </td>
                    <td>
                        @if (item.User.UserName != "rootuser" && item.User.UserName != User.Identity.Name)
                        {
                            <div class="d-flex justify-content-around">
                                <form method="post">
                                    <button class="danger-btn" asp-page-handler="DeleteUser" asp-route-name="@item.User.UserName">Delete</button>
                                </form>
                                @if (Model.RoleList.Count > 0)
                                {
                                    <button type="button" class="blue-btn" data-bs-toggle="modal" data-bs-target="#adduserModal_@item.User.UserName.Replace("@", "").Replace(".", "")">
                                        Add Roles
                                    </button>
                                }
                            </div>
                            <div class="modal fade" id="adduserModal_@item.User.UserName.Replace("@", "").Replace(".", "")" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h1 class="modal-title fs-5" id="exampleModalLabel">Select Roles</h1>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                        </div>
                                        <div class="modal-body">
                                            <form class="px-4 py-3" method="post">
                                                @if (Model.RoleList.Count > 0)
                                                {
                                                    @foreach (var role in Model.RoleList)
                                                    {
                                                        var roles = await UserManager.GetRolesAsync(item.User);
                                                        <div class="mb-1">
                                                            <input id="RoleInput" name="RoleInput" type="checkbox" value="@role.Name" checked="@roles.Contains(role.Name)">
                                                            @Html.Label(role.Name, role.Name)
                                                        </div>
                                                    }
                                                }
                                                <button type="submit" class="blue-btn-10" asp-page-handler="AddRoles" asp-route-name="@item.User.UserName">Add Roles to User</button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>

</div>

<div class="card p-3">
    <div id="drivertoolbar">
        <div class="dropdown">
            <button class="blue-btn-10" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                Add Driver
            </button>
            <form class="px-3 py-3 dropdown-menu" asp-page-handler="DriverCreateUser" method="post">
                <div class="mb-3">
                    <label asp-for="UserEmail" class="form-label">Email address</label>
                    <input type="email" class="form-control" asp-for="UserEmail" placeholder="email@example.com">
                    <span class="text-danger" asp-validation-for="UserEmail"></span>
                </div>
                <button type="submit" class="btn btn-primary">Create Driver</button>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" asp-page="AddDriver">Create Manually</a>
            </form>
        </div>
    </div>
    <h2 class="card-title">Drivers</h2>
    <table id="drivertable"
           data-toggle="table"
           data-search="true"
           data-click-to-select="true"
           data-pagination="true"
           data-id-field="email"
           data-page-list="[10, 25, 50, 100, all]"
           data-sortable="true"
           data-toolbar="#drivertoolbar"
           data-toolbar-align="left">
        <thead>
            <tr>
                <th data-field="state" data-checkbox="true"></th>
                <th data-field="name" data-sortable="true">Name</th>
                <th data-field="email" data-sortable="true">Email</th>
                <th data-field="username" data-sortable="true">Username</th>
                <th data-field="lastLogin" data-sortable="true" data-formatter="dateFormatter">Last Login</th>
                <th data-field="dateCreated" data-sortable="true" data-formatter="dateFormatter">Date Created</th>
                <th data-field="buttons">Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.DriverDetails)
            {
                <tr>
                    <td></td>
                    <td>@item.User.FirstName @item.User.LastName</td>
                    <td>@item.User.Email</td>
                    <td>@item.User.UserName</td>
                    <td>@item.User.LastLogin</td>
                    <td>@item.User.DateCreated</td>
                    <td>
                        
                    </td>
                </tr>
            }
        </tbody>
    </table>

</div>

@section Scripts {
    @*<script src="~/js/Admin/Datatables.js"></script>*@
    <script>
        function dateFormatter(value, row) {
            console.log(value)
            if (value != "") {
                return dayjs(value, 'D/M/YYYY HH:mm:ss a Z').format("ddd, D MMM, YYYY h:mm A")
            }
            return "-"
        }
    </script>
}