Pages/Account/2FA.cshtml.cs
using Spoonful.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Spoonful.Services;
using AspNetCoreHero.ToastNotification.Abstractions;

namespace Spoonful.Pages.Account
{
    public class _2FAModel : PageModel
    {

        private readonly ISmsSender smsSender;
        private readonly IEmailService emailService;
        private readonly INotyfService toastService;
        private UserManager<CustomerUser> userManager { get; }
        private SignInManager<CustomerUser> signInManager { get; }

        public _2FAModel(UserManager<CustomerUser> userManager, SignInManager<CustomerUser> signInManager, ISmsSender smsSender, IEmailService emailService, INotyfService toastService)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
            this.smsSender = smsSender;
            this.emailService = emailService;
            this.toastService = toastService;
        }
        [BindProperty]
        public string OTP { get; set; } 
        [BindProperty]
        public bool RememberMe { get; set; } 
        public List<string> Providers { get; set; }
        public bool SentCode { get; set; }

        [BindProperty]
        public string SelectedProvider { get; set; } 
        public async Task<IActionResult> OnGet(bool rememberMe)
        {
            var user = await signInManager.GetTwoFactorAuthenticationUserAsync();
            if (user == null)
            {
                return RedirectToPage("/Index");
            }
            var providers = await userManager.GetValidTwoFactorProvidersAsync(user);
            Providers = providers.ToList();
            RememberMe = rememberMe;
            return Page();
        }
        public async Task<IActionResult> OnPostVerifyAsync()
        {
            var user = await signInManager.GetTwoFactorAuthenticationUserAsync();
            var providers = await userManager.GetValidTwoFactorProvidersAsync(user);
            Providers = providers.ToList();
            if (OTP == null)
            {
                toastService.Error("Please enter your OTP");
                SentCode = true;
                return Page();
            }
            switch (SelectedProvider)
            {
                case "Authenticator":
                    var authenticatorCode = OTP.Replace(" ", string.Empty).Replace("-", string.Empty);
                    var result = await signInManager.TwoFactorAuthenticatorSignInAsync(authenticatorCode, RememberMe, false);
                    if (result.Succeeded)
                    {
                        toastService.Success("Successfully logged in!");
                        await userManager.UpdateSecurityStampAsync(user);
                        return LocalRedirect("/");
                    }
                    else if (result.IsLockedOut)
                    {
                        toastService.Error("You have been locked out as you had too many invalid attempts. Please try again later");
                        return RedirectToPage("./login");
                    }
                    break;
                default:
                    var resultSignIn = await signInManager.TwoFactorSignInAsync(SelectedProvider, OTP, RememberMe, false);
                    if (resultSignIn.Succeeded)
                    {
                        toastService.Success("Successfully logged in!");
                        await userManager.UpdateSecurityStampAsync(user);
                        return RedirectToPage("/Index");
                    }
                    else if (resultSignIn.IsLockedOut)
                    {
                        toastService.Error("You have been locked out as you had too many invalid attempts. Please try again later");
                        return RedirectToPage("./login");
                    }
                    break;
            }
            ModelState.AddModelError(string.Empty, "Invalid authenticator code.");
            toastService.Error("Invalid OTP");
            SentCode = true;

            return Page();
            //        var user = await signInManager.GetTwoFactorAuthenticationUserAsync();
            //        var providers = await userManager.GetValidTwoFactorProvidersAsync(user);
            //        var result = await signInManager.TwoFactorSignInAsync(providers.FirstOrDefault(), OTP, false, false);
            //        if (result.Succeeded)
            //        {
            //            TempData["FlashMessage.Text"] = "Successfully Logged In";
            //            TempData["FlashMessage.Type"] = "success";
            //await userManager.UpdateSecurityStampAsync(user);
            //return RedirectToPage("/Home");
            //        }
            //        TempData["FlashMessage.Text"] = "Invalid OTP";
            //        TempData["FlashMessage.Type"] = "danger";
            //        return Page();
        }
        public async Task<IActionResult> OnPostAsync()
        {
            var user = await signInManager.GetTwoFactorAuthenticationUserAsync();
            if (user == null)
            {
                throw new InvalidOperationException($"Unable to load two-factor authentication user.");
            }
            switch (SelectedProvider)
            {
                case "SMS":
                    var smscode = await userManager.GenerateTwoFactorTokenAsync(user, SelectedProvider);
                    await smsSender.SendSmsAsync(user.PhoneNumber, $"Security Code: {smscode}");
                    break;
                case "Authenticator":
                    
                    break;
                default:
                    var emailcode = await userManager.GenerateTwoFactorTokenAsync(user, SelectedProvider);
                    emailService.SendEmail(
                        user.Email,
                        "Spoonful Two-Factor Authentication Code",
                        $"This is your 2FA Code: {emailcode}",
                        null,
                        null);
                    break;
            }
            SentCode = true;
            return Page();
        }
        
    }
}

Pages/Account/ChangeEmail.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.WebUtilities;
using Spoonful.Models;
using Spoonful.Services;
using System.ComponentModel.DataAnnotations;
using System.Text.Encodings.Web;
using System.Text;
using AspNetCoreHero.ToastNotification.Abstractions;

namespace Spoonful.Pages.Account
{
    public class ChangeEmailModel : PageModel
    {
        private readonly UserManager<CustomerUser> userManager;
        private IWebHostEnvironment _environment;

        private readonly IEmailService emailService;
        private readonly INotyfService toastService;
        public ChangeEmailModel(UserManager<CustomerUser> userManager, IWebHostEnvironment environment, IEmailService emailService, INotyfService toastService)
        {
            this.userManager = userManager;
            _environment = environment;
            this.emailService = emailService;
            this.toastService = toastService;
        }
        [BindProperty]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        public async Task OnGet()
        {
            var user = await userManager.GetUserAsync(User);
            Email = user.Email;
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                toastService.Error("Email field is required");
                return RedirectToPage();
            }
            var user = await userManager.GetUserAsync(User);

            if (user.Email == Email)
            {
                toastService.Error("Please enter a different email.");
                return RedirectToPage();
            }
            var code = await userManager.GenerateChangeEmailTokenAsync(user, Email);
            code = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(code));
            var callbackUrl = Url.Page(
            "/Account/Confirmation",
                pageHandler: null,
                values: new { username = user.UserName, code = code, purpose = "ChangeEmail", email = Email },
                protocol: Request.Scheme);
            var resultEmail = emailService.SendEmail(
                        Email,
                        "Spoonful Account Change Of Email Address",
                        $"Please verify your email by <a href='{HtmlEncoder.Default.Encode(callbackUrl)}'>clicking here</a>.",
                        null,
                        null);

            if (!resultEmail)
            {
                toastService.Error("Failed to send email");
            }
            toastService.Success("Verification email sent. Please check your email.");
            return RedirectToPage();
        }
    }
}

Pages/Account/ExternalLogin.cshtml.cs
using Spoonful.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.WebUtilities;
using System.ComponentModel.DataAnnotations;
using System.Security.Claims;
using System.Text.Encodings.Web;
using System.Text;
using Microsoft.AspNetCore.DataProtection;
using System.Web;
using Microsoft.AspNetCore.Authorization;
using AspNetCoreHero.ToastNotification.Abstractions;
using Spoonful.Services;

namespace Spoonful.Pages.Account
{
	[AllowAnonymous]
    public class ExternalLoginModel : PageModel
    {
		private readonly SignInManager<CustomerUser> signInManager;
		private IDataProtectionProvider _dataProtectionProvider;
		private readonly UserManager<CustomerUser> userManager; 
		private readonly INotyfService toastService;
		private readonly CustomerUserService customerUserService;

        [BindProperty]
        public Register RModel { get; set; }
        public string? ReturnUrl { get; set; }

        public ExternalLoginModel (SignInManager<CustomerUser> signInManager, UserManager<CustomerUser> userManager, IDataProtectionProvider dataProtectionProvider, INotyfService toastService, CustomerUserService customerUserService)
		{
			this.signInManager = signInManager;
            this.userManager = userManager;
			_dataProtectionProvider = dataProtectionProvider;
			this.toastService = toastService;
            this.customerUserService = customerUserService;
		}
		public IActionResult OnPost(string provider, string? returnUrl = null)
		{
			// Request a redirect to the external login provider.
			var redirectUrl = Url.Page("./ExternalLogin", pageHandler: "Callback", values: new { returnUrl });
			var properties = signInManager.ConfigureExternalAuthenticationProperties(provider, redirectUrl);
			return new ChallengeResult(provider, properties);
		}

		public async Task<IActionResult> OnGetCallbackAsync(string? returnUrl = null, string? remoteError = null)
		{
			returnUrl = returnUrl ?? Url.Content("~/");
			if (remoteError != null)
			{
				//ErrorMessage = $"Error from external provider: {remoteError}";
				return RedirectToPage("./Login", new { ReturnUrl = returnUrl });
			}
			var info = await signInManager.GetExternalLoginInfoAsync();
			if (info == null)
			{
				//ErrorMessage = "Error loading external login information.";
				return RedirectToPage("./Login", new { ReturnUrl = returnUrl });
			}

			// Sign in the user with this external login provider if the user already has a login.
			var result = await signInManager.ExternalLoginSignInAsync(info.LoginProvider, info.ProviderKey, isPersistent: false, bypassTwoFactor: true);
			if (result.Succeeded)
			{
                toastService.Success("Successfully logged in!");
                //_logger.LogInformation("{Name} logged in with {LoginProvider} provider.", info.Principal.Identity.Name, info.LoginProvider);
                return LocalRedirect(returnUrl);
			}
			if (result.IsLockedOut)
			{
                toastService.Error("You have been locked out as you had too many invalid attempts. Please try again later");
                return RedirectToPage("./Login");
			}
			else
			{
				// If the user does not have an account, then ask the user to create an account.
				ReturnUrl = returnUrl;
				if (info.Principal.HasClaim(c => c.Type == ClaimTypes.Email))
				{
                    RModel = new Register
					{
						Email = info.Principal.FindFirstValue(ClaimTypes.Email),
						FirstName = info.Principal.FindFirstValue(ClaimTypes.Name),
					};
				}
				return Page();
			}
		}

        public async Task<IActionResult> OnPostConfirmationAsync(string returnUrl = null)
        {
            returnUrl = returnUrl ?? Url.Content("~/");
            // Get the information about the user from the external login provider
            var info = await signInManager.GetExternalLoginInfoAsync();
            if (info == null)
            {
                //ErrorMessage = "Error loading external login information during confirmation.";
                return RedirectToPage("./Login", new { ReturnUrl = returnUrl });
            }

            if (ModelState.IsValid)
            {
				var protector = _dataProtectionProvider.CreateProtector("MySecretKey");
				var user = new CustomerUser
                {
                    UserName = RModel.UserName,
                    Email = RModel.Email,
                    EmailConfirmed = true,
					FirstName =  RModel.FirstName,
					LastName = RModel.LastName
                };

                var result = await userManager.CreateAsync(user);
                if (result.Succeeded)
                {
                    result = await userManager.AddLoginAsync(user, info);
                    if (result.Succeeded)
                    {
                        await customerUserService.SetUserRoleAsync(user.UserName, Roles.Customer);
                        await signInManager.SignInAsync(user, isPersistent: false, info.LoginProvider);
						await userManager.UpdateSecurityStampAsync(user);
                        toastService.Success("Successfully logged in!");
                        return LocalRedirect(returnUrl);
                    }
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                    toastService.Error(error.Description);

                }
            }

            //ProviderDisplayName = info.ProviderDisplayName;
            ReturnUrl = returnUrl;
            return Page();
        }

		public class Register
		{

            [Required]
            [Display(Name = "Username")]
            public string UserName { get; set; }

            //[Required]
            [Display(Name = "First Name")]
            public string FirstName { get; set; }

            //[Required]
            [Display(Name = "Last Name")]
            public string LastName { get; set; }

            [Required]
            [DataType(DataType.EmailAddress)]
            public string Email { get; set; }

            [Required]
            public bool Terms { get; set; }
        }

	}
}

Pages/Account/ForgetPassword.cshtml.cs
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.WebUtilities;
using System.Text.Encodings.Web;
using System.Text;
using Spoonful.Models;
using Spoonful.Services;
using Microsoft.AspNetCore.Authorization;
using AspNetCoreHero.ToastNotification.Abstractions;
using System.ComponentModel.DataAnnotations;

namespace Spoonful.Pages.Account
{
    [AllowAnonymous]
    public class ForgetPasswordModel : PageModel
    {
        public readonly IEmailService _emailSender;
        public readonly UserManager<CustomerUser> _userManager;
        private readonly INotyfService toastService;


        public ForgetPasswordModel(IEmailService emailSender, UserManager<CustomerUser> userManager, INotyfService toastService)
        {
            _emailSender = emailSender;
            _userManager = userManager;
            this.toastService = toastService;

        }

        [BindProperty]
        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        public void OnGet()
        {
        }
        
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                toastService.Error($"Email Field is required");
                return Page();
            }
            var user = await _userManager.FindByEmailAsync(Email);
            toastService.Information($"A reset password email will be sent to {Email} if it is valid");

            if (user == null)
            {
                return Page();
            }

            var code = await _userManager.GeneratePasswordResetTokenAsync(user);
            code = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(code));
            var callbackUrl = Url.Page(
            "/Account/ResetPassword",
                pageHandler: null,
                values: new { code = code, username = user.UserName },
                protocol: Request.Scheme);

            var result = _emailSender.SendEmail(
                Email,
                "Reset Password",
                $"Please reset your password by <a href='{HtmlEncoder.Default.Encode(callbackUrl)}'>clicking here</a>.",
                null,
                null);
            
            if (!result)
            {
                toastService.Error($"Failed to send email.");

            }
            return Page();
        }
    }
}

Pages/Account/2FA.cshtml
@page
@model Spoonful.Pages.Account._2FAModel
@{
}
@if (!Model.SentCode)
{
    <div class="col-6 mx-auto">
        <form method="post" >
            <input asp-for="RememberMe" type="hidden" />
            <div class="form-outline mb-4">
                <label class="form-label">Choose your 2-Factor Method</label>
                @Html.DropDownListFor(n => n.SelectedProvider, new SelectList(Model.Providers), new { @class="form-select" } )
            </div>
            <!-- Submit button -->
            <button type="submit" class="blue-btn-full">Select</button>

        </form>
    </div>
} else
{
    <div class="col-6 mx-auto">
        <form method="post" asp-page-handler="Verify">
            <input asp-for="RememberMe" type="hidden" />
            <input asp-for="SelectedProvider" type="hidden" />
            <div class="form-outline mb-4">
                <label class="form-label" asp-for="OTP"></label>
                <input type="text" class="form-control" asp-for="OTP"/>
                <span class="text-danger">@Html.ValidationSummary(true)</span>
            </div>
            <!-- Submit button -->
            <button type="submit" class="blue-btn-full">Log in</button>
        </form>
    </div>
}

Pages/Account/ChangeEmail.cshtml
@page
@model Spoonful.Pages.Account.ChangeEmailModel
@{
}
@{
    ViewData["Title"] = "Change Email";
    ViewData["Page"] = "Account";
}
<section class="content-main">
    <div class="content-header">
        <h2 class="content-title">Account setting</h2>
        <br />
    </div>
    <div class="card">
        <div class="card-body">
            <div class="row gx-5">
                @await Html.PartialAsync("_AccountNavBar")
                <div class="col-lg-9">
                    <section class="content-body p-xl-4">
                        <h1 class="tw-text-lg tw-mb-5"><a asp-page="/Account/Index"><i class="bi bi-arrow-left"></i></a></h1>
                        <form method="post">
                            <div class="col-lg-6 mb-3 mx-auto">
                                <label class="form-label">Email</label>
                                <input class="form-control" type="email" placeholder="example@mail.com" asp-for="@Model.Email" />
                                <button type="submit" class="blue-btn-full m-0 mt-2">Change Email</button>
                            </div>
                        </form>
                        
                        <!-- row.// -->
                    </section>
                    <!-- content-body .// -->
                </div>
                <!-- col.// -->
            </div>
            <!-- row.// -->
        </div>
        <!-- card body end// -->
    </div>
    <!-- card end// -->
</section>

Pages/Account/ChangePassword.cshtml
@page
@using AspNetCore.ReCaptcha;
@model Spoonful.Pages.Account.ChangePasswordModel
@{
    ViewData["Page"] = "Account";
}
<section class="content-main">
    <div class="content-header">
        <h2 class="content-title">Account setting</h2>
        <br />
    </div>
    <div class="card">
        <div class="card-body">
            <div class="row gx-5">
                @await Html.PartialAsync("_AccountNavBar")
                <div class="col-lg-9">
                    <section class="content-body p-xl-4">
                        <h1 class="tw-text-lg tw-mb-5"><a asp-page="/Account/Index"><i class="bi bi-arrow-left"></i></a></h1>
                        <form method="post">
                            <div class="col-lg-6 mb-3 mx-auto">
                                <div class="card bg-warning mb-3">
                                    <div class="card-body">
                                        This will require you to log in again
                                    </div>
                                </div>
                                <div class="mb-3">
                                    <label class="form-label">Current Password</label>
                                    <input class="form-control" type="password" asp-for="@Model.OldPassword" />
                                    <span class="text-danger" asp-validation-for="OldPassword"></span>

                                </div>
                                <div class="mb-3">
                                    <label class="form-label">New Password</label>
                                    <input class="form-control" type="password" asp-for="@Model.Password" />
                                    <span class="text-danger" asp-validation-for="Password"></span>

                                </div>
                                <div class="mb-3">
                                    <label class="form-label">Confirm Password</label>
                                    <input class="form-control" type="password" asp-for="@Model.ConfirmPassword" />
                                    <span class="text-danger" asp-validation-for="ConfirmPassword"></span>

                                </div>
                                <button type="submit" class="blue-btn-full m-0 mt-2">Change Password</button>
                            </div>
                        </form>

                        <!-- row.// -->
                    </section>
                    <!-- content-body .// -->
                </div>
                <!-- col.// -->
            </div>
            <!-- row.// -->
        </div>
        <!-- card body end// -->
    </div>
    <!-- card end// -->
</section>

Pages/Account/ChangePhone.cshtml
@page
@model Spoonful.Pages.Account.ChangePhoneModel
@{
    ViewData["Title"] = "Change Email";
    ViewData["Page"] = "Account";
    var sent = Model.Sent;
}
<section class="content-main">
    <div class="content-header">
        <h2 class="content-title">Account setting</h2>
        <br />
    </div>
    <div class="card">
        <div class="card-body">
            <div class="row gx-5">
                @await Html.PartialAsync("_AccountNavBar")
                <div class="col-lg-9">
                    <section class="content-body p-xl-4">
                        <h1 class="tw-text-lg tw-mb-5"><a asp-page="/Account/Index"><i class="bi bi-arrow-left"></i></a></h1>
                        <form method="post">
                            <div class="col-lg-9 mb-3 mx-auto">
                                <label class="form-label">Phone Number</label>
                                <div class="d-flex justify-content-between">
                                    @if (!Model.Sent){
                                        <input class="form-control" type="tel" placeholder="+6512345678" asp-for="@Model.Phone"/>
                                        <button type="submit" class="blue-btn-10 m-0 ms-3">Send Code</button>
                                    } else
                                    {
                                        <input class="form-control" type="tel" placeholder="+6512345678" asp-for="@Model.Phone" readonly/>
                                        <a asp-page="ChangePhone" class="blue-btn-a m-0 ms-3" disabled>Cancel</a>
                                    }
                                </div>
                            </div>
                            @if (Model.Sent)
                            {
                                <div class="col-lg-9 mb-3 mx-auto">
                                    <label class="form-label">Verification Code</label>
                                    <input class="form-control" type="text" asp-for="@Model.Code" />
                                    <button type="submit" class="blue-btn-full m-0 mt-2" asp-page-handler="Verify">Verify</button>
                                </div>
                            }
                        </form>

                        <!-- row.// -->
                    </section>
                    <!-- content-body .// -->
                </div>
                <!-- col.// -->
            </div>
            <!-- row.// -->
        </div>
        <!-- card body end// -->
    </div>
    <!-- card end// -->
</section>

Pages/Account/Confirmation.cshtml
@page
@model Spoonful.Pages.Account.ConfirmationModel
@{
}

Pages/Account/CreateDriver.cshtml
@page
@model Spoonful.Pages.Account.CreateDriverModel
@{
}
<div class="col-6 mx-auto">
    <form method="post">
        <!-- Name input -->
        <div class="form-outline mb-4">
            <input type="text" id="registerFName" class="form-control" asp-for="RAdmin.FirstName" />
            <label class="form-label" asp-for="RAdmin.FirstName"></label>
            <span class="text-danger" asp-validation-for="RAdmin.FirstName"></span>
        </div>

        <!-- Name input -->
        <div class="form-outline mb-4">
            <input type="text" id="registerLName" class="form-control" asp-for="RAdmin.LastName" />
            <label class="form-label" asp-for="RAdmin.LastName"></label>
            <span class="text-danger" asp-validation-for="RAdmin.LastName"></span>
        </div>

        <!-- UserName input -->
        <div class="form-outline mb-4">
            <input type="text" id="registerLName" class="form-control" asp-for="RAdmin.UserName" />
            <label class="form-label" asp-for="RAdmin.UserName"></label>
            <span class="text-danger" asp-validation-for="RAdmin.UserName"></span>
        </div>

        <!-- Password input -->
        <div class="form-outline mb-4">
            <input type="password" id="registerPassword" class="form-control" asp-for="RAdmin.Password" />
            <label class="form-label" asp-for="RAdmin.Password">Password</label>
            <span class="text-danger" asp-validation-for="RAdmin.Password"></span>
        </div>

        <!-- Repeat Password input -->
        <div class="form-outline mb-4">
            <input type="password" id="registerRepeatPassword" class="form-control" asp-for="RAdmin.ConfirmPassword" />
            <label class="form-label" asp-for="RAdmin.ConfirmPassword">Repeat password</label>
            <span class="text-danger" asp-validation-for="RAdmin.ConfirmPassword"></span>
        </div>

        <span class="text-danger">@Html.ValidationSummary(true)</span>

        <!-- Submit button -->
        <button type="submit" class="tw-btn-primary w-100">Register</button>

    </form>

</div>

Pages/Account/ExternalLogin.cshtml
@page
@using AspNetCore.ReCaptcha;
@model Spoonful.Pages.Account.ExternalLoginModel
@{
}
<link rel="stylesheet" href="~/css/Account.css" />
<div class="signin-wrapper">
    <div class="sign-panels">
        <div class="signup">
            <div class="signin-title">
                <span>Register</span>
                <p>Create an account with us.</p>
            </div>

            <div class="or"><span>OR</span></div>

            <form method="post" asp-page-handler="Confirmation" asp-route-returnUrl="@Model.ReturnUrl">
                <div class="form-floating">
                    <input type="text" class="form-control" id="floatingFname" placeholder="First Name" asp-for="RModel.FirstName">
                    <label style="padding-left:30px;" for="floatingFname">First Name</label>
                    <span class="text-danger" asp-validation-for="RModel.FirstName"></span>

                </div>
                <div class="form-floating">
                    <input type="text" class="form-control" id="floatingLname" placeholder="Last Name" asp-for="RModel.LastName">
                    <label style="padding-left:30px;" for="floatingLname">Last Name</label>
                    <span class="text-danger" asp-validation-for="RModel.LastName"></span>

                </div>
                <div class="form-floating">
                    <input type="text" class="form-control" id="floatingUsername" placeholder="Username" asp-for="RModel.UserName">
                    <label style="padding-left:30px;" for="floatingUsername">Username</label>
                    <span class="text-danger" asp-validation-for="RModel.UserName"></span>

                </div>
                <div class="form-floating mb-3">
                    <input type="email" class="form-control" id="floatingEmail" placeholder="Email" asp-for="RModel.Email" readonly>
                    <label style="padding-left:30px;" for="floatingEmail">Email</label>
                    <span class="text-danger" asp-validation-for="RModel.Email"></span>

                </div>

                <input type="checkbox" id="signin-checkbox" asp-for="RModel.Terms">
                <label for="signin-checkbox">I have read and agree to the terms</label>

                <button type="submit" class="btn-signin">Sign Up</button>
                <div class="text-danger mt-3" asp-validation-summary="All"></div>
                <a asp-page="./login" class="btn-login btn-fade">
                    Already have an account, Sign In <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
                </a>
            </form>
        </div>
    </div>
</div>